spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    driver: org.postgresql.Driver
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true

server:
  port: 8081
